from enum import Enum

class E_ASSISTANCE(Enum):
    TABLE = "asistencias"
    ID = "id"
    NUMERO_NOMINA = "numero_nomina"
    NOMBRE = "nombre"
    FECHA = "fecha"
    HORA_ENTRADA = "hora_entrada"
    HORA_SALIDA = "hora_salida"
    DURACION_COMIDA = "duracion_comida"
    TIPO_REGISTRO = "tipo_registro"
    HORAS_TRABAJADAS = "horas_trabajadas"
    TOTAL_HORAS_TRABAJADAS = "total_horas_trabajadas"
    ENTRADA_TURNO = "entrada_turno"
    SALIDA_TURNO = "salida_turno"
    TIEMPO_TRABAJO = "tiempo_trabajo"
    TIEMPO_DESCANSO = "tiempo_descanso"
    RETARDO = "retardo"
    ESTADO = "estado"
    TURNO = "turno"